name: 📊 Generate GitHub Metrics

on:
  schedule: [{cron: "0 6 * * *"}]
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: Katapentakill
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Santiago
          config_display: large
